name: Push to Registry
on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: Container image tag
        required: false
        default: latest
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "e-Budget/e-budget-be"
      - uses: e-Budget/e-budget-actions/.github/actions/setup@main
      - uses: e-Budget/e-budget-actions/.github/actions/package@main
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_BE_REPOSITORY }}:${{ inputs.imageTag }}
          file: e-budget-be/src/main/docker/Dockerfile.jvm
          context: e-budget-be/